services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" ## rabbitmq UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI / Admin
      - "6831:6831/udp" # Envio dos Traces UDP / temporizadores de codigo
      - "14268:14268" # Envio de Traces HTTP
      - "4317:4317" # OTLP / gRPC
      - "4318:4318" # OTLP / http

  api-gateway:
    image: kong:3.9
    environment:
      KONG_DATABASE: 'off'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_GUI_URL: http://localhost:8002
      ORDERS_SERVICE_URL: http://host.docker.internal:3333
      KONG_DECLARATIVE_CONFIG: '/kong/config.yaml'
    volumes:
      - './docker/kong/config.yaml:/kong/config.yaml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000" # Proxy (API)
      - "8001:8001" # API (Admin)
      - "8002:8002" # UI (Admin)
      - "8443:8443" # Proxy SSL (HTTPs)
      - "8444:8444" # API (Admin) (HTTPs)



volumes:
  rabbitmq_data: